### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by dolence** [MaikelvanGorkom/piwigo-tools#1]
Hi! I have an Coppermine installation with many albuns with sub albuns. How can I use this script? I should run it locally or on server? How the files are copied? Looking at the file I just saw configuration options for the DB, how it work?

**Comment by MaikelvanGorkom** [comment]
The script doesn't move images from coppermine to piwigo. It replicates the information from coppermine to piwigo.

The following is my workflow:
**The following has to be done once:**
Fill in the information you have: Connection information for coppermine and Piwigo.
Download your complete copprmine gallery to your local pc
Remove all thumbs_ and normal_files

**Workflow for uploading:**
Create your piwigo album _example Album A, and then in album A, create album 1_
Upload the images from your local repository to the piwigo album 1
Then check the same album in coppermine and remember the number after album in the address bar: thumbnails.php?album=5091
You can check the piwigo album number, but if it's the latest album you don't need to. Grep the catagory number (?/category/92)
**Start the script**
It will ask for the coppermine album id, fill it in.
Then it will ask for the piwigo album (catagory) id, fill it in, or leave blank then it will select the last created album id.
Press enter and then you see an amount of dots, that represent the pictures that have been updated

Example:
_Please enter the coppermine gallery id (check adress bar, the number after 'album='): 1079
Please enter the piwigo category id (Check adress bar, the number after 'category/'
(Don't enter anything and press enter for the last category): 5790
...._

After this i remove the coppermine album and the pictures locally and go to the next album.

Hopefully this will explain it for you. If not, don't hesitate to ask!

**Comment by mjbostwick** [comment]
What version of mysql Connector are you using? I'm not a python user and have modified your script with my pertinent info but am getting an error when I run the script 
Please enter the coppermine gallery id (check adress bar, the number after 'album='): 58
Please enter the piwigo category id (Check adress bar, the number after 'category/'
(Don't enter anything and press enter for the last category): 6
Traceback (most recent call last):
  File "C:\Users\mjbos\Downloads\migrate-coppremine-info-to-piwigo.py", line 62, in <module>
    PIWI_Cursor.execute(PIWI_UpdateQRY)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\mjbos\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\mysql\connector\cursor.py", line 416, in execute
    self._connection.cmd_query(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._stmt_partition["mappable_stmt"],
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        read_timeout=self._read_timeout,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        write_timeout=self._write_timeout,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\mjbos\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\mysql\connector\opentelemetry\context_propagation.py", line 97, in wrapper
    return method(cnx, *args, **kwargs)
  File "C:\Users\mjbos\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\mysql\connector\_decorating.py", line 89, in handle_cnx_method
    raise err
  File "C:\Users\mjbos\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\mysql\connector\_decorating.py", line 85, in handle_cnx_method
    return cnx_method(cnx, *args, **kwargs)
  File "C:\Users\mjbos\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\mysql\connector\connection.py", line 984, in cmd_query
    result = self._handle_result(
        self._send_cmd(
    ...<6 lines>...
        write_timeout,
    )
  File "C:\Users\mjbos\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\mysql\connector\_decorating.py", line 89, in handle_cnx_method
    raise err
  File "C:\Users\mjbos\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\mysql\connector\_decorating.py", line 85, in handle_cnx_method
    return cnx_method(cnx, *args, **kwargs)
  File "C:\Users\mjbos\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\mysql\connector\connection.py", line 745, in _handle_result
    raise get_exception(packet)
mysql.connector.errors.ProgrammingError: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 1
